;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2020/6/11 12:56:43

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

